export * from "./Query";
export * from "./Mutation";
export * from "./User";
export * from "./Patient";
export * from "./Appointment";
export * from "./Checkup";
export * from "./PatientVitals";
export * from "./Role";
export * from "./AuthPayload";